# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 666c20a516cdec642510f4376f24b7594866e32f905fef06f9f9278368c5faf08619db7471021de229bec7e5b55520c0336733de851102d68c5c676b3abf04e4

test:
  secret_key_base: 384bc45a82a1ae0724b91029031fe7f136c1803528dfcb0a1cb3805d70b17a4493d55b7f69eff8f0a5c82312923ac6b41fcf4d6f3b11f3ae6982453335effb11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
